kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: denytor
  namespace: istio-system
rules:
  - apiGroups: 
    - security.istio.io
    resources: 
    - authorizationpolicies
    verbs: 
    - get
    - list 
    - watch 
    - create 
    - update 
    - patch 
    - delete