kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: denytor
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: denytor
  namespace: istio-system
roleRef:
  kind: Role
  name: denytor
  apiGroup: "rbac.authorization.k8s.io"